### ISSUE TITLE
Interpretation of "normal" argument

### ISSUE THREAD

**Issue by qdread** [NEON-biodiversity/Ostats#3]
Hi Arya, I looked at some of the documentation you made and it looks great. I did find one issue -- the interpretation of the "normal" or "norm" argument. It has nothing to do with assuming that the data are normally distributed. In this case, normalization refers to setting the area under the curve equal to 1. So the documentation for that parameter should read something like: 
```
if TRUE, the area under all density functions is normalized to 1, if FALSE, the area under all density functions is proportional to the number of observations in that group.
```
Hopefully that makes sense!

**Comment by yyue-r** [comment]
@qdread Hi Quentin, thank you very much for pointing it out! I vaguely realized it during our meeting and made a note to check through all my work related to "norm", but I missed this since Github is linked to another of my email that I do not check as frequently. Sorry for the delay but I will recheck the documentation!
